# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMercadao1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mercadao1(self):
    self.driver.get("https://mercadao.pt/store/pingo-doce")
    self.driver.set_window_size(1920, 1080)
    self.driver.find_element(By.XPATH, "//div[@id=\'onetrust-button-group\']/div[3]/button").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'onetrust-pc-sdk\']/div/div[3]/div/button").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("Peixe")
    self.driver.find_element(By.ID, "search").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-store-sidebar > .sidebar-item:nth-child(3) .pdo-middle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(6) .pdo-middle:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-block > .pdo-dropdown-filter .pdo-block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(2) .ng-star-inserted").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_13vWVcI0E4manTyoSeQTsY")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-column:nth-child(3) .pdo-inline-block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(1) .ui-chkbox-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-clean-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-label > .pdo-block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown-item:nth-child(3) .ui-radiobutton-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".P9eg53AkHYfXRP7gt5njS:nth-child(33) .pdo-block > .pdo-block").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-add-btn").click()
    self.driver.find_element(By.ID, "postalCode").click()
    self.driver.find_element(By.ID, "postalCode").send_keys("6000-041")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("Carne")
    self.driver.find_element(By.CSS_SELECTOR, ".-active > .pdo-inline-block > .ng-star-inserted").click()
    self.driver.find_element(By.CSS_SELECTOR, ".aOo3xeyCHWOqd4xvqS8hK").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-btn > .pdo-button-bag").click()
  
