# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://mercadao.pt/store/pingo-doce")
    self.driver.set_window_size(1054, 800)
    self.driver.find_element(By.ID, "onetrust-pc-btn-handler").click()
    self.driver.find_element(By.CSS_SELECTOR, ".save-preference-btn-handler").click()

def main():
    pytest.main(['-v', 'test_untitled.py'])

if __name__ == '__main__':
    main()
  
