# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtokart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtokart(self):
    self.driver.get("https://www.mercadao.pt/store/pingo-doce/product/salada-americana-vitacress-200-g")
    self.driver.set_window_size(768, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-add-btn").click()
    self.driver.execute_script("window.scrollTo(0,400)")
    self.driver.find_element(By.ID, "postalCode").click()
    self.driver.find_element(By.ID, "postalCode").send_keys("6000-041")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.XPATH, "//div[@id=\'swiper-wrapper-a46bda7de71ecd7d\']/div[2]/pdo-product-item/article/a/picture/cl-image/img").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-add-btn").click()
  
