# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtocart(self):
    self.driver.get("https://www.mercadao.pt/store/pingo-doce/product/salada-americana-vitacress-200-g")
    self.driver.set_window_size(768, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-icon-dismiss").click()
    self.driver.find_element(By.CSS_SELECTOR, ".-remove").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-add-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-store-sidebar > .sidebar-item:nth-child(3) .pdo-middle").click()
    self.driver.find_element(By.LINK_TEXT, "Arroz").click()
    element = self.driver.find_element(By.LINK_TEXT, "Política de Privacidade")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".P9eg53AkHYfXRP7gt5njS:nth-child(2) .pdo-block > .pdo-block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdo-add-btn").click()
  
