package Modalities;

import scxmlgen.interfaces.IOutput;

public enum Output implements IOutput {

    // CHANGE_COLOR_TRIANGULO_AZUL("[FUSION][CHANGE_COLOR][TRIANGULO][AZUL]"),
    // CHANGE_COLOR_TRIANGULO_VERDE("[FUSION][CHANGE_COLOR][TRIANGULO][VERDE]"),
    // CHANGE_COLOR_TRIANGULO_CINZENTO("[FUSION][CHANGE_COLOR][TRIANGULO][CINZENTO]"),
    // CHANGE_COLOR_TRIANGULO_VERMELHO("[FUSION][CHANGE_COLOR][TRIANGULO][VERMELHO]"),
    // CHANGE_COLOR_TRIANGULO_BRANCO("[FUSION][CHANGE_COLOR][TRIANGULO][BRANCO]"),
    // CHANGE_COLOR_TRIANGULO_ROSA("[FUSION][CHANGE_COLOR][TRIANGULO][ROSA]"),
    // CHANGE_COLOR_TRIANGULO_AMARELO("[FUSION][CHANGE_COLOR][TRIANGULO][AMARELO]"),
    // CHANGE_COLOR_TRIANGULO_PRETO("[FUSION][CHANGE_COLOR][TRIANGULO][PRETO]"),
    // CHANGE_COLOR_TRIANGULO_LARANJA("[FUSION][CHANGE_COLOR][TRIANGULO][LARANJA]"),

    // CHANGE_COLOR_QUADRADO_AZUL("[FUSION][CHANGE_COLOR][QUADRADO][AZUL]"),
    // CHANGE_COLOR_QUADRADO_VERDE("[FUSION][CHANGE_COLOR][QUADRADO][VERDE]"),
    // CHANGE_COLOR_QUADRADO_CINZENTO("[FUSION][CHANGE_COLOR][QUADRADO][CINZENTO]"),
    // CHANGE_COLOR_QUADRADO_VERMELHO("[FUSION][CHANGE_COLOR][QUADRADO][VERMELHO]"),
    // CHANGE_COLOR_QUADRADO_BRANCO("[FUSION][CHANGE_COLOR][QUADRADO][BRANCO]"),
    // CHANGE_COLOR_QUADRADO_ROSA("[FUSION][CHANGE_COLOR][QUADRADO][ROSA]"),
    // CHANGE_COLOR_QUADRADO_AMARELO("[FUSION][CHANGE_COLOR][QUADRADO][AMARELO]"),
    // CHANGE_COLOR_QUADRADO_PRETO("[FUSION][CHANGE_COLOR][QUADRADO][PRETO]"),
    // CHANGE_COLOR_QUADRADO_LARANJA("[FUSION][CHANGE_COLOR][QUADRADO][LARANJA]"),

    // CHANGE_COLOR_CIRCULO_AZUL("[FUSION][CHANGE_COLOR][CIRCULO][AZUL]"),
    // CHANGE_COLOR_CIRCULO_VERDE("[FUSION][CHANGE_COLOR][CIRCULO][VERDE]"),
    // CHANGE_COLOR_CIRCULO_CINZENTO("[FUSION][CHANGE_COLOR][CIRCULO][CINZENTO]"),
    // CHANGE_COLOR_CIRCULO_VERMELHO("[FUSION][CHANGE_COLOR][CIRCULO][VERMELHO]"),
    // CHANGE_COLOR_CIRCULO_BRANCO("[FUSION][CHANGE_COLOR][CIRCULO][BRANCO]"),
    // CHANGE_COLOR_CIRCULO_ROSA("[FUSION][CHANGE_COLOR][CIRCULO][ROSA]"),
    // CHANGE_COLOR_CIRCULO_AMARELO("[FUSION][CHANGE_COLOR][CIRCULO][AMARELO]"),
    // CHANGE_COLOR_CIRCULO_PRETO("[FUSION][CHANGE_COLOR][CIRCULO][PRETO]"),
    // CHANGE_COLOR_CIRCULO_LARANJA("[FUSION][CHANGE_COLOR][CIRCULO][LARANJA]"),

    // Redundant
    EXEC_QUIT_ACTION("[FUSION][QUIT]"),
    EXEC_SCROLL_UP_ACTION("[FUSION][SCROLL][UP]"),
    EXEC_SCROLL_DOWN_ACTION("[FUSION][SCROLL][DOWN]"),
    EXEC_OPEN_PRODUCT_ACTION("[FUSION][OPEN_PRODUCT]"),

    // Complementary
    EXEC_HELP_ACTION("[FUSION][HELP]"),
    EXEC_HELP_CARRINHO_ACTION("[FUSION][HELP][CARRINHO]"),
    EXEC_HELP_CODIGO_POSTAL_ACTION("[FUSION][HELP][CODIGO POSTAL]"),
    EXEC_HELP_LOJA_ACTION("[FUSION][HELP][LOJA]"),
    EXEC_HELP_OPERACOES_ACTION("[FUSION][HELP][OPERACOES]"),
    EXEC_HELP_PRODUTO_ACTION("[FUSION][HELP][PRODUTO]"),
    EXEC_HELP_TODAS_ACTION("[FUSION][HELP][TODAS]"),
    
    EXEC_ADD_TO_CART_ACTION("[FUSION][ADD_TO_CART]"),

    // Single
    EXEC_INSERT_NUMBER_ACTION("[FUSION][INSERT_NUMBER]"),

    ;

    private String event;

    Output(String m) {
        event = m;
    }

    public String getEvent() {
        return this.toString();
    }

    public String getEventName() {
        return event;
    }
}
