/* 
  *   Speech.java generated by speechmod 
 */

package Modalities;

import scxmlgen.interfaces.IModality;

public enum Speech implements IModality {

	// CHANGE_COLOR_AZUL("[SPEECH][CHANGE_COLOR][AZUL]", 1500),
	// CHANGE_COLOR_VERDE("[SPEECH][CHANGE_COLOR][VERDE]", 1500),
	// CHANGE_COLOR_CINZENTO("[SPEECH][CHANGE_COLOR][CINZENTO]", 1500),
	// CHANGE_COLOR_VERMELHO("[SPEECH][CHANGE_COLOR][VERMELHO]", 1500),
	// CHANGE_COLOR_BRANCO("[SPEECH][CHANGE_COLOR][BRANC]", 1500),
	// CHANGE_COLOR_ROSA("[SPEECH][CHANGE_COLOR][ROSA]", 1500),
	// CHANGE_COLOR_AMARELO("[SPEECH][CHANGE_COLOR][AMARELO]", 1500),
	// CHANGE_COLOR_PRETO("[SPEECH][CHANGE_COLOR][PRETO]", 1500),
	// CHANGE_COLOR_LARANJA("[SPEECH][CHANGE_COLOR][LARANJA]", 1500),

	QUIT_APP("[SPEECH][QUIT]", 0),
	SCROLL_UP("[SPEECH][SCROLL][UP]", 0),
	SCROLL_DOWN("[SPEECH][SCROLL][DOWN]", 0),
	OPEN_PRODUCT("[SPEECH][OPEN_PRODUCT]", 0),
	ADD_TO_CART("[SPEECH][ADD_TO_CART]", 5000),

	ASK_HELP("[SPEECH][HELP]", 5000),
	ASK_HELP_CARRINHO("[SPEECH][HELP][CARRINHO]", 5000),
	ASK_HELP_PRODUTO("[SPEECH][HELP][PRODUTO]", 5000),
	ASK_HELP_PRODUTOS("[SPEECH][HELP][PRODUTOS]", 5000),
	ASK_HELP_CODIGO_POSTAL("[SPEECH][HELP][CODIGO_POSTAL]", 5000),
	ASK_HELP_MORADA("[SPEECH][HELP][MORADA]", 5000),
	ASK_HELP_LOJA("[SPEECH][HELP][LOJA]", 5000),
	ASK_HELP_OPERACOES("[SPEECH][HELP][OPERACOES]", 5000),
	ASK_HELP_GESTOS("[SPEECH][HELP][GESTOS]", 5000),
	ASK_HELP_TODAS("[SPEECH][HELP][TODAS]", 5000),

	
	;

	private String event;
	private int timeout;

	Speech(String m, int time) {
		event = m;
		timeout = time;
	}

	@Override
	public int getTimeOut() {
		return timeout;
	}

	@Override
	public String getEventName() {
		return event;
	}

	@Override
	public String getEvName() {
		return getModalityName().toLowerCase() + event.toLowerCase();
	}

}
